### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by SweetGeneral** [theSupermacy/k8s-auditor#1]
Would like to add readme file for this repo. Following points need to be discussed in order to do that:-

- What problem are we trying to solve?
- How do we approach the problem?
- Is there any existing solution for the problem? If yes, what does is lack?

**Comment by theSupermacy** [comment]
We wanted to build a global config search in the cluster and also store events so that they can be queried and properly audited.
The main things which we want to capture are:-

- Config Maps: So any change in config maps would be captured in this system and later can be used to query over it. This system can be extended to make a trail for changes in config maps. This can also be served as a single place for config search for the overall cluster.
- Events: Kubernetes events are short-lived and can vanish after a certain time period. This will store all the events with proper metadata so that they can make proper sense and can be used for auditing purposes.
- Secrets: This basic approach can be extended for secrets as well. Of course, we need some layer that can mask important data which will go into the query engine. 

I have done a quick search and didn't find anything which will solve this issue. So if we find anything else we will deprecate this project and start contributing in that project. Meanwhile, we can start building this project now.
